# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  name: Default

variables:
  buildDir: '$(System.DefaultWorkingDirectory)\target'

stages:
- stage: Build
  displayName: "Build Stage"
  jobs:
  - job: Build
    displayName: "Build Job"
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.11'
        jdkArchitectureOption: 'x64'
        goals: 'clean compile package'

- stage: Test
  displayName: "Test Stage"
  dependsOn: Build
  jobs:
  - job: Test
    displayName: "Test Job"
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.11'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**\surefire-reports\TEST-*.xml'
        goals: 'test'

- stage: Deliver
  displayName: "Deliver Stage"
  dependsOn: Test
  jobs:
  - job: Deliver
    displayName: "Deliver Job"
    steps:
    - script: |
        echo "Debug: Checking $(buildDir)"
        if not exist "$(buildDir)\deliverables" mkdir "$(buildDir)\deliverables"
        echo "Copying JAR files to deliverables"
        for %%f in ("$(buildDir)\*.jar") do (
          echo Copying %%f
          copy "%%f" "$(buildDir)\deliverables\"
        )
        echo "Copying test result files to deliverables"
        for %%f in ("$(buildDir)\**\surefire-reports\TEST-*.xml") do (
          echo Copying %%f
          copy "%%f" "$(buildDir)\deliverables\"
        )
      displayName: "Prepare Deliverables"

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(buildDir)\deliverables'
        artifact: 'java-app'
        publishLocation: 'pipeline'
